server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

